#!/bin/bash

echo "==================================="
echo "PASO 4: Actualizar Webhook en Supabase"
echo "==================================="
echo ""
echo "Necesitas obtener tu Supabase Access Token y ejecutar estos comandos:"
echo ""
echo "1. Ir a: https://supabase.com/dashboard/account/tokens"
echo "2. Generar un nuevo token (si no tienes uno)"
echo "3. Copiar el token"
echo "4. Ejecutar estos comandos (reemplaza YOUR_TOKEN):"
echo ""
echo "   export SUPABASE_ACCESS_TOKEN=YOUR_TOKEN"
echo ""
echo "   supabase secrets set \\"
echo "     FLOW_WEBHOOK_URL=\"https://witty-bush-0d65a3d0f.2.azurestaticapps.net/api/flow-webhook\" \\"
echo "     --project-ref owewtzddyykyraxkkorx"
echo ""
echo "5. Redeploy create-flow-payment edge function:"
echo ""
echo "   cd supabase/functions"
echo "   supabase functions deploy create-flow-payment --project-ref owewtzddyykyraxkkorx"
echo ""
echo "==================================="
echo "PASO 5: Probar el Flujo Completo"
echo "==================================="
echo ""
echo "1. Abrir la app: https://witty-bush-0d65a3d0f.2.azurestaticapps.net"
echo "2. Hacer login"
echo "3. Agregar productos al carrito"
echo "4. Ir a checkout"
echo "5. Completar datos de envío"
echo "6. Procesar pago con tarjeta de prueba Flow:"
echo "   - Tarjeta: 4051885600446623"
echo "   - CVV: 123"
echo "   - Fecha: Cualquier fecha futura"
echo ""
echo "7. Completar pago en Flow sandbox"
echo "8. Verificar redirección exitosa"
echo "9. ¡NO deberías recibir email de error de Flow!"
echo ""
echo "==================================="
echo "Verificar Logs en Azure"
echo "==================================="
echo ""
echo "Ver logs del webhook:"
echo ""
echo "   az monitor app-insights query \\"
echo "     --app shopping-cart-angular \\"
echo "     --resource-group laboratorio \\"
echo "     --analytics-query \"traces | where message contains 'flow-webhook' | order by timestamp desc | take 10\""
echo ""
