#!/bin/bash

# Branch Protection Setup Guide
# Este script documenta los pasos para configurar branch protection en GitHub
# No puede ejecutarse automáticamente - debes seguir los pasos en GitHub UI

echo "🔒 Branch Protection Rules Setup Guide"
echo "======================================"
echo ""
echo "⚠️  IMPORTANTE: Estos pasos deben realizarse manualmente en GitHub"
echo "    GitHub API requiere una GitHub App para automatizar esto"
echo ""
echo "📍 URL: https://github.com/claudiojara/angular-shopping-cart/settings/branches"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🟢 REGLA 1: Protección para 'main' (Producción)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Branch name pattern: main"
echo ""
echo "✅ Require a pull request before merging"
echo "   - Required number of approvals: 1"
echo "   - ✅ Dismiss stale pull request approvals when new commits are pushed"
echo "   - ✅ Require review from Code Owners"
echo ""
echo "✅ Require status checks to pass before merging"
echo "   - ✅ Require branches to be up to date before merging"
echo "   - Status checks required:"
echo "     • quality-checks"
echo "     • deploy-production"
echo ""
echo "✅ Require conversation resolution before merging"
echo ""
echo "✅ Require linear history"
echo ""
echo "✅ Do not allow bypassing the above settings"
echo ""
echo "✅ Restrict who can push to matching branches"
echo "   - Limit to: Maintainers"
echo ""
echo "❌ Allow force pushes: Disabled"
echo "❌ Allow deletions: Disabled"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🟡 REGLA 2: Protección para 'develop' (Staging)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Branch name pattern: develop"
echo ""
echo "✅ Require a pull request before merging"
echo "   - Required number of approvals: 1"
echo "   - ✅ Dismiss stale pull request approvals when new commits are pushed"
echo "   - ❌ Require review from Code Owners (opcional)"
echo ""
echo "✅ Require status checks to pass before merging"
echo "   - ✅ Require branches to be up to date before merging"
echo "   - Status checks required:"
echo "     • quality-checks"
echo "     • deploy-staging"
echo ""
echo "✅ Require conversation resolution before merging"
echo ""
echo "✅ Require linear history"
echo ""
echo "⚠️  Do not allow bypassing the above settings"
echo "   - Recomendado: Enabled (puedes hacer bypass en emergencias)"
echo ""
echo "❌ Restrict who can push to matching branches: Disabled"
echo "   (Permite pushes directos en emergencias)"
echo ""
echo "❌ Allow force pushes: Disabled"
echo "❌ Allow deletions: Disabled"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📝 PASO ADICIONAL: Crear CODEOWNERS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Crear archivo: .github/CODEOWNERS"
echo ""
echo "Contenido sugerido:"
echo "---"
echo "# Global owners"
echo "*       @claudiojara"
echo ""
echo "# Core services"
echo "/src/app/services/          @claudiojara"
echo "/src/app/core/              @claudiojara"
echo ""
echo "# CI/CD"
echo "/.github/workflows/         @claudiojara"
echo "/scripts/                   @claudiojara"
echo "/.azure/                    @claudiojara"
echo ""
echo "# Documentation"
echo "*.md                        @claudiojara"
echo "/docs/                      @claudiojara"
echo "---"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "⚙️  CONFIGURACIÓN ADICIONAL: Merge Settings"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📍 URL: https://github.com/claudiojara/angular-shopping-cart/settings"
echo ""
echo "En 'Pull Requests' section:"
echo ""
echo "✅ Allow squash merging"
echo "   - Default to pull request title"
echo "   - Default commit message: Pull request title and description"
echo ""
echo "✅ Allow rebase merging"
echo ""
echo "❌ Allow merge commits (bloqueado por linear history)"
echo ""
echo "✅ Automatically delete head branches"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ CHECKLIST DE VERIFICACIÓN"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Después de configurar, verifica que:"
echo ""
echo "[ ] Branch protection para 'main' está activa"
echo "[ ] Branch protection para 'develop' está activa"
echo "[ ] Status checks requeridos están seleccionados"
echo "[ ] Linear history está habilitado"
echo "[ ] Squash merge es el método default"
echo "[ ] Auto-delete head branches está habilitado"
echo "[ ] CODEOWNERS está creado (si aplica)"
echo "[ ] No puedes hacer force push a main/develop"
echo "[ ] No puedes hacer merge sin approval"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📚 Documentación completa: docs/BRANCH_PROTECTION.md"
echo ""
echo "✅ Una vez configurado, las ramas estarán protegidas contra:"
echo "   • Merges sin review"
echo "   • Merges con CI fallando"
echo "   • Force pushes destructivos"
echo "   • Borrado accidental"
echo ""
echo "🎉 ¡Configuración completa para flujo GitFlow seguro!"
